### ISSUE TITLE
env.sha3 unresolveable

### ISSUE THREAD

**Issue by NatPDeveloper** [AntelopeIO/cdt#16] opened 2022-08-17 21:10 UTC
**Description of error:**

When you run leap with the new cdt without enabling the crypto feature you get `env.sha3 unresolveable`, even when not using the feature.

**Steps to reproduce:**

Try and deploy a new cdt contract without enabling the crypto feature.

**Desired behavior:**

No error and when the feature is being used, a better error code perhaps that specifies the feature that needs to be enabled.

**Comment by stephenpdeos** [comment] 2022-08-18 17:43
For now, we will include the crypto primitive host functions in a separate header file so this error doesn't occur for those not trying to use this feature.

**Comment by linh2931** [comment] 2022-08-24 12:57
@NatPDeveloper I started Leap release 3.1 without enabling crypto protocol feature, and pushed a simple contract compiled by CDT release/3.0's cdt-cpp; but I could not reproduce the problem. Could you share your contract and exact steps to reproduce the problem?

**Comment by NatPDeveloper** [comment] 2022-08-24 14:56
unable to reproduce at this time, not sure what changed will reopen if necessary

**Comment by benjiewheeler** [comment] 2022-08-29 17:30
I'm facing this issue as well

#### Steps to reproduce:
*On a fresh Ubuntu 18.04 VM*
* install leap `leap-3.1.0-rc4-ubuntu18.04-x86_64.deb`
* install cdt `cdt_3.0.0-rc2_amd64.deb`
* run a vanilla nodeos local chain
* compile the contract `cdt-cpp --abigen -I include -o dummy.wasm dummy.cpp`
* deploy it `cleos set contract dummy $PWD dummy.wasm dummy.abi -p dummy@active`

```cpp
#include <eosio/crypto.hpp>
#include <eosio/eosio.hpp>
using namespace eosio;

CONTRACT dummy : public contract
{
public:
    using contract::contract;

    ACTION hi(name nm);

    using hi_action = action_wrapper<"hi"_n, &dummy::hi>;
};
```

```cpp
#include "dummy.hpp"

ACTION dummy::hi(name nm)
{
    sha256("abc", 3);
}
```

If I comment this line `sha256("abc", 3);` and recompile and deploy, it works just fine

**Comment by linh2931** [comment] 2022-08-29 18:17
This should be fixed by https://github.com/AntelopeIO/cdt/pull/21. Not sure if you could build a CDT on https://github.com/AntelopeIO/cdt/tree/expose_crypto_primitives to give it a try.

**Closed** 2022-09-23 01:32 UTC

**Comment by marijnbent** [comment] 2022-12-26 10:56
where can I find cleos?
